### ISSUE TITLE
TCP Latency test are not supported for external client mode

### ISSUE THREAD

**Issue by scrollins** [microsoft/ethr#100]
I'm getting the following error when trying to execute a tcp latency test 
```
root@myserver:~# ethr -6 -c haproxy:9999 -m x -t l -n 25
Error: "Latency" test for "TCP" is not supported.

Please use "ethr -h" for ethr command line arguments.
```
According to the [status](https://github.com/microsoft/ethr#status), it says that latency tests are supported

**Comment by scrollins** [comment]
I think I have figured out what the issue is. It looks like the latency tests are not supported when using the external client mode. I was able to get these working with running the ethr client on the same host as the server. Any plans to support this? The readme doesnt say anything about external client mode not supporting certain types of tests

**Comment by scrollins** [comment]
Closing this since I was able to get it working w/ using external mode

**Comment by gbrancovici-samsung** [comment]
> Closing this since I was able to get it working w/ using external mode

How?

**Comment by gbrancovici-sam** [comment]
> Closing this since I was able to get it working w/ using external mode

Hi, how?
