### ISSUE TITLE
Bandwidth tests for buffer size/packet size

### ISSUE THREAD

**Issue by scrollins** [microsoft/ethr#101]
What's the behavior supposed to be for the buffer parameter on a bandwidth test?
 I've been taking tcpdumps thinking that it would increase the actual packet size but that doesnt seem to be the case. My test looks like 
``` ethr -c ethr-server -t b -i 1 -l 2mb -d 5s
ethr -c ethr-server -t b -i 1 -l 40mb -d 5s
ethr -c ethr-server -t b -i 1 -l 2gb -d 5s
```
The packet length ramps up from 64 to 22848 and never changes based on what buffer size I give it. I saw an issue that was closed https://github.com/microsoft/ethr/issues/16. I'm curious as to how one would go about crafting a packet size or what the buffer size is doing. If there is no way to do this, would you guys be open to PRs implementing that functionality? Thanks

**Comment by pgmsft** [comment]
Yes, I would be open to a PR on this, but not sure if this would work with TCP. TCP is a streaming protocol, so even if you use buffer as 64b, it may still create packets that are larger than 64 bytes by buffering multiple sends. Further, if you use larger size, say 64K, then depending upon if large send offload is enabled, TCP would still need to break packets in MSS sized segments.
