### ISSUE TITLE
UDP performance on server side

### ISSUE THREAD

**Issue by maxsharabayko** [microsoft/ethr#106]
Hi.
I am running a UDP network performance test with ethr.
The client reports sending speed, but the server reports only 0 bits/s. Why is that?

UDP/TCP ports 4200-4300 are open, so the traffic should pass. The same experiment with HTTP works well.

I need to know the speed of receiving,

### Server
`ethr -s -ports control=4287,tcp=4299,udp=4201,http=4289,https=4288`

```
[RemoteAddress]  Proto   Bits/s   Conn/s    Pkt/s   Latency 
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
[**.**.***.***]    UDP        0
Ending Bandwidth test from **.**.***.***
```

### Client

`ethr -c IP -n 1 -p udp -t b -ports control=4287,tcp=4299,udp=4201,http=4289,https=4288 -l 64KB`

```
[ ID]   Protocol    Interval      Bits/s
[  6]     UDP      000-001 sec     1.90G
[  6]     UDP      001-002 sec     1.89G
[  6]     UDP      002-003 sec     1.89G
[  6]     UDP      003-004 sec     1.89G
[  6]     UDP      004-005 sec     1.89G
[  6]     UDP      005-006 sec     1.89G
[  6]     UDP      006-007 sec     1.89G
[  6]     UDP      007-008 sec     1.89G
[  6]     UDP      008-009 sec     1.89G
[  6]     UDP      009-010 sec     1.89G
```

**Comment by pgmsft** [comment]
Can you please delete ethrc.log and ethrs.log, rerun the test and share the newly generated log files from both server and client?

**Comment by maxlovic** [comment]
@pgmsft Please check the attachment.
This time server had some non-zero value at the start.

[ethrc.log](https://github.com/microsoft/ethr/files/3750855/ethrc.log)
[ethrs.log](https://github.com/microsoft/ethr/files/3750856/ethrs.log)

**Comment by pgmsft** [comment]
There seems to be some kind of NAT going on the traffic. I would suspect that is causing problem. Do you not see the problem if you use default ports?

**Comment by maxlovic** [comment]
The experiments were performed in Azure. The latest one was between Ubuntu VMs, located in EU west and US west. So might be related to NAT.
Tried on a local switch, and both server and client report UDP throughput.

Are there any steps to make it work in Azure?
Not sure if default ports will help, but could be an option. Sadly, can't repeat the experiment in Azure soon enough.
