### ISSUE TITLE
Display unicode network interface name.

### ISSUE THREAD

**Issue by nogarder77** [microsoft/ethr#107]
https://github.com/microsoft/ethr/blob/fe09eed5fbce59a67e03295019b6258a1d7f8d3f/ui.go#L165

Currently, unicode network interface name is not displayed correctly.
Please change the code
xoff++ ==> xoff = xoff + 2

Thanks a lot.

![if_err](https://user-images.githubusercontent.com/17287772/70418268-764ef200-1aa6-11ea-9e6c-f56b70d2ea74.png)

**Comment by pgmsft** [comment]
Can you please submit a patch?

**Comment by nogarder77** [comment]
I tested it with change above, and it fix the problem.

**Comment by pgmsft** [comment]
Can you please submit a pull request? I can merge it. Otherwise I will add the change in few days when I get a chance.

**Comment by nogarder77** [comment]
Please ignore this issue, I tested with latest source code, it display UTF8 interface name.
![ethr_test](https://user-images.githubusercontent.com/17287772/92189207-16507500-ee99-11ea-9861-26ec8fadeaa5.png)
