### ISSUE TITLE
Results on Mac differ greatly from results on Linux on the same network, Mac results are 20x higher than expected.

### ISSUE THREAD

**Issue by natethinks** [microsoft/ethr#113]
I am running a UDP bandwidth test on two devices on my network, testing speed to an external server I have set up.

My internet connection is pretty stable at ~300Mb/s and I'm on wireless so the Linux results seem accurate, the Mac OS results are pretty far off though.

This is the command I am running.
`ethr -c {external} -t b -p udp -l 8kb`

These are the results.
Ubuntu 19.10:
```- - - - - - - - - - - - - - - - - - - - - - -
[ ID]   Protocol    Interval      Bits/s
[  6]     UDP      000-001 sec   217.98M
[  6]     UDP      001-002 sec   223.49M
[  6]     UDP      002-003 sec   234.50M
[  6]     UDP      003-004 sec   241.34M
[  6]     UDP      004-005 sec   239.42M
[  6]     UDP      005-006 sec   235.07M
[  6]     UDP      006-007 sec   239.17M
[  6]     UDP      007-008 sec   219.14M
[  6]     UDP      008-009 sec   222.78M
[  6]     UDP      009-010 sec   220.67M
```

Mac OS 10.14.6:
```- - - - - - - - - - - - - - - - - - - - - - -
[ ID]   Protocol    Interval      Bits/s
[ 12]     UDP      000-001 sec     5.62G
[ 12]     UDP      001-002 sec     5.99G
[ 12]     UDP      002-003 sec     6.01G
[ 12]     UDP      003-004 sec     6.12G
[ 12]     UDP      004-005 sec     6.09G
[ 12]     UDP      005-006 sec     6.16G
[ 12]     UDP      006-007 sec     6.13G
[ 12]     UDP      007-008 sec     6.12G
[ 12]     UDP      008-009 sec     6.15G
```

**Comment by pgmsft** [comment]
@natethinks You should measure UDP results on the receiver side. UDP allows sender to send more data than receiver can handle, so client side is showing data it is sending, while server will show data that is actually being received based on actual network bandwidth. It is also possible for different OS to have different send performance.
