### ISSUE TITLE
Is UDP bandwidth test supported?

### ISSUE THREAD

**Issue by Shanfang** [microsoft/ethr#116]
Thanks for making this great tool. I am using this to test some UDP traffic. This is not exactlly an issue, just want to get some confirmations. It is marked in the status that UDP bandwidth is YES(I believe this indicates that UDP bandwidth test is supported). But UDP bandwidth is also mentioned in the TODO list. I want to use this bandwidth test feature for UDP. Can someone please help clarify if this is supported or not?

- [ ] Support for UDP bandwidth & latency testing

Protocol | Bandwidth | Connections/s | Packets/s | Latency
-- | -- | -- | -- | --
TCP | Yes | Yes | No | Yes
UDP | Yes | NA | Yes | No

**Comment by pgmsft** [comment]
UDP bandwidth test is supported. UDP latency test is not supported.

**Comment by Shanfang** [comment]
> UDP bandwidth test is supported. UDP latency test is not supported.

Thanks, but I am not seeing 0 bits on service side. I noticed there is an open issue mentioning that this could be related to NAT. There is NAT happening in my case.

**Comment by pgmsft** [comment]
Most likely NAT would cause this problem. I would need to check with NAT in picture, I haven't done that yet. Can you test without NAT?

**Comment by pgmsft** [comment]
I am closing the issue due to inactivity. Please reopen if you still see the problem.
