### ISSUE TITLE
Client side runtime error

### ISSUE THREAD

**Issue by Shanfang** [microsoft/ethr#120]
I got below runtime err while starting client with this command: **ethr.exe -c 100.0.1.4 -p tcp -ports control=8060,tcp=8080,udp=8000,http=9000,https=9090 -t l**
Any idea what is going on here and how to fix it?

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x6893e7]

goroutine 1 [running]:
main.establishSession(0x200000000, 0x3e8000000001, 0x3e8, 0xc003234140, 0xb, 0xc000096070, 0x7a52a0, 0xc00003a620)
        /home/travis/gopath/src/github.com/Microsoft/ethr/client.go:74 +0x5a7
main.runClient(0x200000000, 0x3e8000000001, 0x3e8, 0x2540be400, 0x0, 0xc00004e090, 0x9)
        /home/travis/gopath/src/github.com/Microsoft/ethr/client.go:28 +0xdc
main.main()
        /home/travis/gopath/src/github.com/Microsoft/ethr/ethr.go:382 +0x7f8

**Comment by pgmsft** [comment]
I will look at it, which version are you using?

**Comment by pgmsft** [comment]
I am not able to repro, please try on latest version.
