### ISSUE TITLE
documentation for external mode...

### ISSUE THREAD

**Issue by maceip** [microsoft/ethr#121]
it's not clear what external mode does, or when it should be used; both for the client and the server. I might look at the source and submit a pull request to better explain it when I get some free time.

**Comment by pgmsft** [comment]
External mode is for standalone usage where you use Ethr as a server but use a non-Ethr client, or vice versa. 

Example, say you want to measure connection latency to www.microsoft.com, you can do:
ethr -m x -c www.microsoft.com:443 -t cl -4 -g 1s

This would measure TCP connection latency to microsoft.com at every 1s interval.

**Comment by pgmsft** [comment]
#130 fixes it.
