### ISSUE TITLE
Feature request: add mtr support

### ISSUE THREAD

**Issue by BradErz** [microsoft/ethr#124]
Would it be possible to consider adding mtr support across the different protocols? obviously mtr support on linux is pretty first class. But on windows trying to get a tcp mtr output requires installing npcap and https://github.com/0xcafed00d/tracetcp.

It would be amazing to see the support added.

**Comment by pgmsft** [comment]
What is mtr?

**Comment by pgmsft** [comment]
ICMP mtr support is added. TCP/UDP may get added later.
