### ISSUE TITLE
IP Parameter Not Allowed for Server Mode

### ISSUE THREAD

**Issue by orware** [microsoft/ethr#139]
The docs mentions an `-ip` parameter is allowed for the Server Mode so it can bind to a specific IP, but when trying that out, ethr outputs back the help documentation (because it's not an allowed parameter within the program, and the docs it outputs to me directly at that point also reflect that since the `-ip` parameter is missing in that output).

This is with the current Windows client (v.0.90).

**Comment by pgmsft** [comment]
This is available in latest release. Thanks.
