### ISSUE TITLE
openSUSE Leap 15 (server) + Ubuntu 18.04 and Win 7 (clients)

### ISSUE THREAD

**Issue by MikhailKasimov** [Microsoft/Ethr#19]
Hello!

```README.md``` can be updated -- have successfully tested on ```openSUSE Leap 15``` (as a server) + ```Ubuntu 18.04``` and ```Windows 7 SP 1``` ( as the clients).

Binaries were downloaded from links of ```Download``` section.

Here left is ```openSUSE Leap 15``` machine and ```Ubuntu 18.04``` on the right hand.
![imag1288](https://user-images.githubusercontent.com/7167300/49644357-ddb00d00-fa20-11e8-837c-e0afdfaeb19d.jpg)

```Ubuntu 18.04``` + ```Windows 7 SP 1``` (from virtual machine).
![imag1289](https://user-images.githubusercontent.com/7167300/49644395-00dabc80-fa21-11e8-84de-50197e920a44.jpg)

Thanks!

**Comment by pgmsft** [comment]
Updated readme fe0524d50497e2751e65fb4690dc12817a56730b
