### ISSUE TITLE
MacOS Support - go build fails (779d5c1)

### ISSUE THREAD

**Issue by machinemob** [Microsoft/Ethr#2]
MacOS(Mojave)10.14.1 (18B75)
go1.11.2 darwin/amd64 (homebrew)
ITerm2 Build 3.2.6

$ go build
./serverui.go:88:2: undefined: hideCursor
./serverui.go:89:2: undefined: blockWindowResize
./stats.go:33:2: undefined: getNetDevStats
./stats.go:37:2: undefined: getTcpStats

**Comment by ipankajg** [comment]
This would need Mac OS support. I don't use Mac so can't fix it. If someone can submit a PR that would be great. A file similar to plt_windows and plt_linux needs to be created for MAC os.

**Comment by pgmsft** [comment]
This is because currently MacOS is not supported. I don't use Mac so if someone can submit a PR that would be great. You would need to provide a follow for Mac similar to plt_windows and plt_linux.

**Comment by hellt** [comment]
the key here would be to find how one can get interface counters on a mac os x, since it has no `/proc`

**Comment by pgmsft** [comment]
Yes, either we can add dummy implementation and the stats feature doesn't work, which is optional and only used in UI view on server, or we can find ways to build it e.g. by referring to netstat code. I believe OSX uses some API for such information.

**Comment by pgmsft** [comment]
This is great, thanks @fsouza. I can merge the PR once it is ready. Please note: hideCursor may just need to call tm.HideCursor or move it to 0,0 row, column. blockWindowResize is optional and it is not implemented on Linux either.

**Comment by golmaall** [comment]
@pgmsft , @fsouza  I can help with this

**Comment by dreness** [comment]
@fsouza hiya - I gave your fork a try, and in general it seems to work fine, although in server mode, the interface stats are quite inaccurate. Here's a short demo of the server view: https://asciinema.org/a/215997

The data reported by the client is accurate.

**Comment by fsouza** [comment]
@dreness oh 😱 I'll investigate what's going on later today or tomorrow, thanks for trying it out!

**Comment by fsouza** [comment]
@dreness it should be good now, I did something wrong when generating ifMsghdr2, it was missing padding and the underlying bytes were getting interpreted incorrectly.

**Comment by pgmsft** [comment]
Closing the issue, as this is mostly fixed by: 6fcc37915d10441824772ddcf94f521480a2ba7a

**Comment by sdwvit** [comment]
@pgmsft please updated readme/docs that macos is now supported

**Comment by pgmsft** [comment]
Updated.
