### ISSUE TITLE
MacOS TCP statistics support

### ISSUE THREAD

**Issue by pgmsft** [Microsoft/ethr#28]
The current Mac OS support does not return TCP stats. This enhancement will bring Mac support on par.

**Comment by girishmotwani** [comment]
I have a Patch for this

**Comment by girishmotwani** [comment]
https://github.com/Microsoft/Ethr/pull/30

**Comment by mahaangelmahi** [comment]
Not getting

**Comment by pgmsft** [comment]
Completed by #30
