### ISSUE TITLE
ubuntu build failed

### ISSUE THREAD

**Issue by wusphinx** [Microsoft/Ethr#3]
in my ubuntu
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
```
go version
```
go version go1.6.2 linux/amd64
```
and I want to build `Ethr`
```
➜  Ethr git:(master) go build
# github.com/Microsoft/Ethr
./client.go:326: undefined: sort.SliceStable
./server.go:334: undefined: sort.SliceStable
./stats.go:34: undefined: sort.SliceStable
./utils.go:224: undefined: syscall.RawConn
./utils.go:228: ct.SyscallConn undefined (type *net.TCPConn has no field or method SyscallConn)
➜  Ethr git:(master)
```
As we can see，`sort.SliceStable` is not supported by go version 1.6.2,  it is supported until [go1.8](https://blog.golang.org/go1.8). So, It will be better if you can add some guidance about go version or other which is supported by `Ethr`

**Comment by pgmsft** [comment]
Thank you for reporting this issue, will update the documentation tomorrow.

**Comment by pgmsft** [comment]
I have updated the documentation. Is it ok to close the issue?

**Comment by wusphinx** [comment]
> I have updated the documentation. Is it ok to close the issue?

:+1:Well done
