### ISSUE TITLE
Bad error message when bad duration passed in

### ISSUE THREAD

**Issue by lylex** [Microsoft/Ethr#31]
When I try the client, I find it raises a bad error message when I pass in a bad duration for `-d` option, e.g. `./Ethr -c 10.29.96.153 -d 10`.

And the error message is `Invalid value "%!s(*string=0xc000097cc0)" specified for parameter "-d".`

**Comment by lylex** [comment]
I will submit a PR since it is a tiny bug.

**Comment by pgmsft** [comment]
Merged: ca2bbcc
