### ISSUE TITLE
proposed : using ci tools  

### ISSUE THREAD

**Issue by u5surf** [Microsoft/ethr#43]
I propose that this repository should be used continuous integration service.
to check code lint, to be analyzing sorce code(go vet or gofmt) , and test automatically when each pull request will be coming.
e.g. https://docs.travis-ci.com/user/languages/go/
I think travis-ci has a high affinity for github.

**Comment by pgmsft** [comment]
We will look into this and how to get it setup.

**Comment by pgmsft** [comment]
Thank you for adding travis yml file. I have enabled build for this in travis now.
