### ISSUE TITLE
vs. iperf?

### ISSUE THREAD

**Issue by snobu** [Microsoft/Ethr#5]
How does this compare to the "standard", meaning [iperf3](https://iperf.fr/iperf-download.php)?
May i suggest you add a few words about that to the README? This isn't about which is better, it's more about how is this different.

**Comment by pgmsft** [comment]
I have added a small section there as a richer comparison maybe better done in a blog post. The short summary is that for TCP bandwidth measurements, Ethr is similar to iPerf3. The main difference is that Ethr is multi-threaded (by using goroutines) and can scale much better. For example, it can go to 1024 parallel streams whereas iPerf3 doesn't allow beyond 64. On the other hand, iPerf3 has a lot more features than Ethr such as throttled measurements, UDP throughput support.

Ethr also supports more measurements such as connections/s, packets/s & latency, all in a single tool, as well as multiple clients running against a single server.

Over time, we hope to add more features to Ethr (also hoping for contributions from others) to make it more feature rich.

Hope this provides some context and details.
