### ISSUE TITLE
-4 and -6 parameters are unrecognizable by ethr

### ISSUE THREAD

**Issue by MikhailKasimov** [Microsoft/ethr#75]
Hello!

Subj.

Despite on ```-4 ``` and ```-6 ``` parameters, described in ```README.md``` file in ```Common Parameters``` paragraph, they are unrecognizable by ```ethr``` and are not displayed in help-info on ```-h``` key and when ```ethr``` is given without parameters.

Use-cases I've tested on: ```./ethr -4 - s``` and ```./ethr -4 -c <server_IP_to_connect_to>```. Both of them return ```ethr```'s help-info.

Thanks!

**Comment by pgmsft** [comment]
Thanks for the report. Did you try the latest version or prebuilt binaries?

**Comment by pgmsft** [comment]
This was happening because the build was v0.1 and these options were in latest source code, so you needed to build from source. I have now release v0.2.1 with pre-built binaries. Please use that build and it should work.
