### ISSUE TITLE
Client error when testing more than one instance with same server

### ISSUE THREAD

**Issue by abraaocaldas** [microsoft/ethr#76]
Clients : Android 8 / Android 9 Pie 
Server : Ubuntu Server 18.04

Compiled from latest commit : 65627a0

Steps to reproduce:

Start the server
Initialize the first client with ethr -c IP -p udp
Initialize the second client with ethr -c IP -p -r udp

second client will print this output:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23a5e4]

goroutine 1 [running]:
main.establishSession(0x100000001, 0x3e8000000001, 0x1000003e8, 0x4420010890, 0xf, 0x44200b6070, 0x34f4c0, 0x442005fb10)
        /root/go/src/ethr/client.go:74 +0x4a4
main.runClient(0x100000001, 0x3e8000000001, 0x1000003e8, 0x2540be400, 0x0, 0x7fc9bfa873, 0xd)
        /root/go/src/ethr/client.go:28 +0xc0
main.main()
        /root/go/src/ethr/ethr.go:374 +0x708

Then the server will be waiting forever for the UDP packets.

One more thing, when client sends the UDP packets, it will fill the pipe , in my case client tried to send 1Gbit of data in one try.

**Comment by pgmsft** [comment]
There is a missing return statement in client. I would fix it later. Did you get the error message that duplicate session is rejected? Only one client from same machine for one type of test is supported currently. The server doesn't wait as it terminates the connection.

I am not sure about buffer filling problem. Can you provide more details?

**Comment by abraaocaldas** [comment]
> There is a missing return statement in client. I would fix it later. Did you get the error message that duplicate session is rejected? Only one client from same machine for one type of test is supported currently. The server doesn't wait as it terminates the connection.

Oh, I see, well I tried with clients on different "machines" and I didn't get any error message about duplicated session.
By the way, TCP works fine even if there is different machines testing at same time, only UDP has this issue.

> I am not sure about buffer filling problem. Can you provide more details?

I double checked and the problem only happens on two clients connect to same server and perform the test at same time. 1-to-1 have no issue.

Thanks!

**Comment by pgmsft** [comment]
Please note that -r is only supported for TCP. I would add validation, as well as fix the crashing bug soon.
