### ISSUE TITLE
IP version output to display (server side)

### ISSUE THREAD

**Issue by MikhailKasimov** [microsoft/ethr#77]
Hello!

IP version output to display, when server side is in use. E.g.:

```
./ethr -4 -s
Accepting IP version: ipv4
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 8888 for control plane
```

```
./ethr -6 -s
Accepting IP version: ipv6
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 8888 for control plane
```

```
./ethr -4 -6 -s
Accepting IP version: ipv4, ipv6
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 8888 for control plane
```

```
./ethr -s
Accepting IP version: ipv4, ipv6
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 8888 for control plane
```

Can be useful for dropping specified packets from client side. Personally, after some tests I have 0.5 ratio of initial connections due to multiple TCP6 ```CLOSE_WAIT``` connections (12 hours) in ```ss -tunlp``` output.

**Comment by pgmsft** [comment]
We would look into adding the extra message for IP version. For the 0.5 ratio of connections, which test are you running? Connections/s?

**Comment by pgmsft** [comment]
I see, can you elaborate on what you mean by 0.5 ratio? Also are you running ethr -c in a loop or with -d 0 to run it forever?

**Comment by MikhailKasimov** [comment]
```what you mean by 0.5 ratio?``` --> 850-900 Mb falls down to 450-550 Mb.

 ``` Also are you running ethr -c in a loop or with -d 0 to run it forever? ``` --> in a loop.

Now I'm currently trying to reproduce it on ```0.2.1```. Will let you know after having (un-)success.
