### ISSUE TITLE
Go module instead of dep

### ISSUE THREAD

**Issue by koushki** [Microsoft/ethr#78]
Hi,

Wouldn't make more sense to use go-module instead of dep?

**Comment by pgmsft** [comment]
Could you elaborate why that would make more sense? Someone contributed the dep changes. As this is my first golang project,I still haven't gotten time to analyze all aspects. If there are good reasons and someone can submit a PR, I would accept it.

**Comment by koushki** [comment]
Sure, go-module has direct support from Go command, also you are no longer depended to GOPATH directory, means you can work in any workplace you want 💃 ! but also some other reasons which maybe you can find it with better explanations here  https://github.com/golang/dep/issues/1959 (go-module vs dep) and https://golang.org/doc/go1.11#modules
I feel since it is officially a language feature, it will be more and more popular in the future.

go module is introduced with go1.11, it can be kind of downside if you are strong to support 1.10!

BTW, I can create a PR if you agree with this.

**Comment by pgmsft** [comment]
@radu-matei You added dep support initially. Would you be ok if we move to go modules? Do you see any downsides?

@koushki I am fine with the change and agree with your assessment. Let's wait for 2 days for Radu to reply if he has any concerns, and then move forward. I assume travis integration etc. would work seamlessly with it, right?

**Comment by radu-matei** [comment]
Hi, all!
There are a few thing I'd like to note around this change:

- it forces people to upgrade the Go version
- there are still subtle issues with modules which are continuously fixed through patch upgrades to Go
- `dep` is stable

That being said, modules are going to be the standard going forward, and it would make sense to add support.

If we test everything, make sure nothing breaks, and have clear instructions on how to contribute, I'm all for it, and I'd be glad to review a PR with the changes.
