### ISSUE TITLE
Suggestion about main package split, add test code.

### ISSUE THREAD

**Issue by mcauto** [Microsoft/ethr#80]
Hello ! I like this project.

I want to contribute this project.

but it is difficult.

I think ethr has big main package.

Further, ethr doesn't have test code.

I think open source project should have test code.

Test code makes it easy to contribute and makes it guessing that main intending of project. then contributer can proper pull request.

And I think It can be split logger, server, client, ui, util, etc package.

**Comment by pgmsft** [comment]
If someone can contribute changes for test code, I would accept the PR. The code base is small (~3000 lines) so no plan to break up in multiple packages right now.
