### ISSUE TITLE
centos6.5 ethr error

### ISSUE THREAD

**Issue by tujiaw** [microsoft/ethr#91]
CentOS release 6.5 (Final)

1.
[root@node172 ethr]# ./ethr -s
Listening on 9999 for TCP bandwidth tests
Listening on 9998 for TCP conn/s tests
Listening on 9996 for TCP latency tests
Listening on 9899 for HTTP bandwidth tests
Listening on 9799 for HTTPS bandwidth tests
Listening on 9896 for HTTP latency tests
Listening on 8888 for control plane
panic: runtime error: slice bounds out of range

goroutine 88 [running]:
github.com/microsoft/ethr/internal/stats.buildNetDevStat(0xc0012c4180, 0x7f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/sumscope/ethr/internal/stats/linux.go:84 +0x3f8
github.com/microsoft/ethr/internal/stats.osStats.GetNetDevStats(0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/sumscope/ethr/internal/stats/linux.go:60 +0x302
main.getNetworkStats(0xa7b100, 0x50f7a5cd, 0xa5e5a0, 0x50ed975a, 0x0, 0x0)
        /opt/sumscope/ethr/stats.go:19 +0x3f
main.emitStats()
        /opt/sumscope/ethr/stats.go:115 +0x133
main.startStatsTimer.func1(0xc000fc6500)
        /opt/sumscope/ethr/stats.go:86 +0x3b
created by main.startStatsTimer
        /opt/sumscope/ethr/stats.go:82 +0x66

2.
[root@node172 ethr]# ./ethr -c "172.16.73.153"
Connecting to host [172.16.73.153], port 9999
[  6] local 172.16.75.172 port 48967 connected to 172.16.73.153 port 9999
- - - - - - - - - - - - - - - - - - - - - - -
[ ID]   Protocol    Interval      Bits/s
[  6]     TCP      000-001 sec   701.18M
panic: runtime error: slice bounds out of range

goroutine 1341 [running]:
github.com/microsoft/ethr/internal/stats.buildNetDevStat(0xc000f70280, 0x7f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000045e30, 0x6)
        /opt/sumscope/ethr/internal/stats/linux.go:84 +0x3f8
github.com/microsoft/ethr/internal/stats.osStats.GetNetDevStats(0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/sumscope/ethr/internal/stats/linux.go:60 +0x302
main.getNetworkStats(0xa7b100, 0x5fb9733c, 0xa5e5a0, 0x5faf3302, 0x0, 0x0)
        /opt/sumscope/ethr/stats.go:19 +0x3f
main.emitStats()
        /opt/sumscope/ethr/stats.go:115 +0x133
main.startStatsTimer.func1(0xc000f56140)
        /opt/sumscope/ethr/stats.go:86 +0x3b
created by main.startStatsTimer
        /opt/sumscope/ethr/stats.go:82 +0x66

**Comment by boyan-soubachov** [comment]
The problem seems to be that the `/proc/net/dev` file format is not what we're expecting. 

I've added logging and sanity checks to throw a proper error here: #93
